INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Dog Adoption", "Animals", 500, "3-1-19", "3-15-2019");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Mental Health Awareness", "Health", 600, "3-16-19", "3-20-19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Food Drive", "Community", 700, "3-1-19", "3-15-19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Ocean Cleanup", "Environment",5000, "4-1-19","4-15-19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Climate Change", "Eco", 50000, "6-1-19", "6-15-19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Autism Awareness", "Mental Health",600, "7-1-19", "8-15-19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Breast Cancer Awareness", "Health", 600000, "8-8-19", "8-9-19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Toy Drive", "Children", 700, "3-3-19", "3-16-19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Cat Adoption", "Pets", 650, "3-2-19", "3-17-19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Meals on Wheels", "Homeless", 800, "6-5-19", "6-6-19");

INSERT INTO users (name, age) VALUES ("Jim Brown", 28);
INSERT INTO users (name, age) VALUES ("Joe White", 30);
INSERT INTO users (name, age) VALUES ("Claire Paper", 30);
INSERT INTO users (name, age) VALUES ("Emma Wall", 40);
INSERT INTO users (name, age) VALUES ("Lauren Seed", 24);
INSERT INTO users (name, age) VALUES ("Ben Little", 31);
INSERT INTO users (name, age) VALUES ("Sean More", 28);
INSERT INTO users (name, age) VALUES ("Mike Eve", 41);
INSERT INTO users (name, age) VALUES ("Time Strange", 27);
INSERT INTO users (name, age) VALUES ("George Bond", 19);
INSERT INTO users (name, age) VALUES ("Alice Stone", 49);
INSERT INTO users (name, age) VALUES ("Betty Crocker", 76);
INSERT INTO users (name, age) VALUES ("Elvis Rockstar", 36);
INSERT INTO users (name, age) VALUES ("Marilyn Monroe", 27);
INSERT INTO users (name, age) VALUES ("Kathy Red", 43);
INSERT INTO users (name, age) VALUES ("Lucy Sky", 65);
INSERT INTO users (name, age) VALUES ("Don Jon", 65);
INSERT INTO users (name, age) VALUES ("Ned Ted", 34);
INSERT INTO users (name, age) VALUES ("Bo Gardner", 54);
INSERT INTO users (name, age) VALUES ("Lisa Frank", 21);

INSERT INTO pledges (amount, user_id, project_id) VALUES (65, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 1, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 2, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 6, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (70, 3, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 6, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 7, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 13, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 15, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 17, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 18, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 19, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 20, 2);
