INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Dog Adoption", "Animals", 500, "3-1-19", "3-15-2019");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Mental Health Awareness", "Health", 600, "3-16-19", "3-20-19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Food Drive", "Community", 700, "3-1-19", "3-15-19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Ocean Cleanup", "Environment",5000, "4-1-19","4-15-19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Climate Change", "Eco", 50000, "6-1-19", "6-15-19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Autism Awareness", "Mental Health",600, "7-1-19", "8-15-19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Breast Cancer Awareness", "Health", 600000, "8-8-19", "8-9-19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Toy Drive", "Children", 700, "3-3-19", "3-16-19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Cat Adoption", "Pets", 650, "3-2-19", "3-17-19");
INSERT INTO projects (id, title, category, funding_goal, start_date, end_date) VALUES ("Meals on Wheels", "Homeless", 800, "6-5-19", "6-6-19");

INSERT INTO users (name, age) VALUES ("Jim Brown", 28);
INSERT INTO users (name, age) VALUES ("Joe White", 30);
INSERT INTO users (name, age) VALUES ("Claire Paper", 30);
INSERT INTO users (name, age) VALUES ("Emma Wall", 40);
INSERT INTO users (name, age) VALUES ("Lauren Seed", 24);
INSERT INTO users (name, age) VALUES ("Ben Little", 31);
INSERT INTO users (name, age) VALUES ("Sean More", 28);
INSERT INTO users (name, age) VALUES ("Mike Eve", 41);
INSERT INTO users (name, age) VALUES ("Time Strange", 27);
INSERT INTO users (name, age) VALUES ("George Bond", 19);
INSERT INTO users (name, age) VALUES ("Alice Stone", 49);
INSERT INTO users (name, age) VALUES ("Betty Crocker", 76);
INSERT INTO users (name, age) VALUES ("Elvis Rockstar", 36);
INSERT INTO users (name, age) VALUES ("Marilyn Monroe", 27);
INSERT INTO users (name, age) VALUES ("Jim Brown", 28);
INSERT INTO users (name, age) VALUES ("Jim Brown", 28);
INSERT INTO users (name, age) VALUES ("Jim Brown", 28);
INSERT INTO users (name, age) VALUES ("Jim Brown", 28);
INSERT INTO users (name, age) VALUES ("Jim Brown", 28);
INSERT INTO users (name, age) VALUES ("Jim Brown", 28);

